name: Build and Push Docker image

on:
  pull_request:
    branches: ['release']

env:
  LATEST_TAG: innocentde/osu-flex:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./assets/docker/linux_arm64/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ env.LATEST_TAG }}